### ISSUE TITLE
Missing assertion

### ISSUE THREAD

**Issue by leonid-shevtsov** [railsware/indeed#2]
Sometimes Indeed responds with an error page instead of the JSON data you're expecting. This results in the following exception:

```
Yajl::ParseError: lexical error: invalid char in json text. <!DOCTYPE HTML PUBLIC "-//IETF/ (right here) ------^ 
indeed-0.1.0/lib/indeed.rb:74:in `http_get'
```

I think the exception should be caught

**Comment by bogdan** [comment]
We need to check if response status is success before trying to parse it.
